### ISSUE TITLE
Great Plugin

### ISSUE THREAD

**Issue by 404Ninja** [SoaringCats/IdentityCrisis#1]
I was testing it out on my server, and overall loved it. There are however three things that I have suggestions for.
1. Make it so if you use /changename example &4Bob his name is the color red on the tab list instead of being &4Bob
2. Get rid of the npc that has your name that only you can see.
3. Make it remember who your disguised as long term so it saves who your disguised as when the server restarts or you reload all the plugins.

**Comment by jamietech** [comment]
It should save username changes to the configuration file, does it not?
I'll fix player list colouring in a few minutes :)

**Comment by jamietech** [comment]
Uploaded to DBO waiting on approval.
Fixed by b13f3f5f78da356e8fa3afbe2a64322b9091b15a
