### ISSUE TITLE
Ghost

### ISSUE THREAD

**Issue by Dementual** [SoaringCats/IdentityCrisis#2]
It appears to leave an NPC of the player when their name changes including your own.

**Comment by jamietech** [comment]
Does this happen for users other than yourself?

**Comment by Dementual** [comment]
Yes, it happens to all my users.

**Comment by mbax** [comment]
I warned jamie not to release this until 1.2 of the TagAPI was out :P

There's a little... surprise... in 1.1 that results in duping.

**Comment by jamietech** [comment]
Yay!
Edit: @Dementual is this fixed with latest TagAPI version?

**Comment by jamietech** [comment]
Closing due to lack of reply. :3
