### ISSUE TITLE
Character limitation.

### ISSUE THREAD

**Issue by xalixilax** [SoaringCats/IdentityCrisis#3]
It would be nice if we can get longer character because on my server, 
we got something like this:
&4[&fA&4]&f xalixilax 
but it's too much character so it would be nice if it's possible.

**Comment by jamietech** [comment]
Sorry for the delay in response, @xalixilax 
Unfortunately Minecraft has a limit on characters for player names and will not allow names longer than 16 characters (which is the limit for any Minecraft username on Minecraft.net!). If you wish to ask a Mojangsta for help (ex: a suggestion), I'm sure you can do so at http://help.mojang.net
Thanks for using IdentityCrisis!

**Comment by xalixilax** [comment]
Ok thank you for your answer!
