### ISSUE TITLE
Please Update to 1.4.6

### ISSUE THREAD

**Issue by brinabo** [SoaringCats/IdentityCrisis#4]
Please update this plugin to 1.4.6 thank you! I love the plugin!

**Comment by jamietech** [comment]
Can you please provide an error log. Thanks. :)

**Comment by brinabo** [comment]
There are no errors, it works great still :) sorry to bother you
I was just afraid there were incompatibilities

**Comment by jamietech** [comment]
There won't ever be.
Thanks for using and attempting to report issues!

**Comment by jamietech** [comment]
:love_letter:
