### ISSUE TITLE
Needs To Be Updated - Errors occur - Includes Pastebin

### ISSUE THREAD

**Issue by brinabo** [SoaringCats/IdentityCrisis#6]
Hello, when I use IdentityCrisis with the latest bukkit version (1.4.7-R1.0) it doesn't change my name and instead my console gets constantly spammed with this message:
http://dev.bukkit.org/paste/7103/
Indefinitely until I /stop the server.

When I use older versions of craftbukkit (1.4.6) it works perfectly fine.
Thank you and sorry for not giving more information last time, my email did not receive a reply message from github.

**Comment by jamietech** [comment]
If you look _very_ closely you can see that IdentityCrisis isn't mentioned once, rather, RankSuite seems to be an issue.
