### ISSUE TITLE
Formatcodes in names?

### ISSUE THREAD

**Issue by o0Julia0o** [SoaringCats/IdentityCrisis#7]
hi,

it would be nice, if format-codes in names would be possible. But everytime i do it in config-file, it´s erased:

  Allow plugin to check for updates?
  Disable if paranoid.
names:
  Julia: &6Julia
  jamietech: &kjamietech

The magic-format like i added to jamietech would be very nice to have: http://ess.khhq.net/mc

thx

julia :)

**Comment by jamietech** [comment]
Hi Julia!

Colour codes like that will work, you just need to set them in game.
If the configuration is modified whilst the game is running it will be wiped on shutdown/reload.

**Comment by o0Julia0o** [comment]
oh thx, yes - and in config, too:
'&kNAME' for magic-format for user: "NAME".
