### ISSUE TITLE
Playerlistename + chatname

### ISSUE THREAD

**Issue by o0Julia0o** [SoaringCats/IdentityCrisis#8]
hi, it would be nice, if there would be a option in config-file to change the playerlistname & the chat-name & welcome+leaving-message-name, too.

thx

Julia :)

**Comment by jamietech** [comment]
Coding now. :)

**Comment by o0Julia0o** [comment]
nice :)

1 thing - which would be very nice. Could the chat-name be another nickname then the tagname & playerlistname? The playerlist & tagname works perfekt on roll-play-servers - you can decrypt them with magic-format.

But it would be nice, if the players can have another nick f.e. with green name in the chat. That would be very comfortable.

So:
1. Playername
2. Nickname for nametag + Tablist (can be the same)
3. Nickname for chat

is that possible?

thx

julia :)

**Comment by jamietech** [comment]
Unfortunately the chat nickname is out of the scope of this plugin.
IdentityCrisis is only to change a player's name discretely.

If you do in-fact wish to change the chat display name and add a 'nickname' I unfortunately have to suggest that you find another plugin to do so.

Sorry!
