### ISSUE TITLE
Skin Issues?

### ISSUE THREAD

**Issue by Dorian-Fendrel** [SoaringCats/IdentityCrisis#9]
I run a fairly new roleplay server, and i was going to impliment this for the names. The issue Im getting, is when i switch their name, they get the steve skin. We use RP skins for everything, so you can see where this is an issue. Am i making a mistake or is it just not compatible. I am using TagApi as well.

**Comment by jamietech** [comment]
Hiya!

Unfortunately due to the way TagAPI works, skins are indicative of the DISPLAYED NAME. I can look at a fix using scoreboards if you want.

Thanks for using IdentityCrisis :)

**Comment by jamietech** [comment]
dc7eb2734ad441676af574b9388d19dfa9353893

**Comment by Dorian-Fendrel** [comment]
Yes, please find me a work around. i love the plugin, its lightweight and effective. That skin issue is the only one I have.
